// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.5.0
// source: Zhaoh0401.proto

package sample_package_0401

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Zhaoh0401Client is the client API for Zhaoh0401 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Zhaoh0401Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type zhaoh0401Client struct {
	cc grpc.ClientConnInterface
}

func NewZhaoh0401Client(cc grpc.ClientConnInterface) Zhaoh0401Client {
	return &zhaoh0401Client{cc}
}

func (c *zhaoh0401Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/sample_module_0401.sample_package_0401.Zhaoh0401/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Zhaoh0401Server is the server API for Zhaoh0401 service.
// All implementations must embed UnimplementedZhaoh0401Server
// for forward compatibility
type Zhaoh0401Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedZhaoh0401Server()
}

// UnimplementedZhaoh0401Server must be embedded to have forward compatible implementations.
type UnimplementedZhaoh0401Server struct {
}

func (UnimplementedZhaoh0401Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedZhaoh0401Server) mustEmbedUnimplementedZhaoh0401Server() {}

// UnsafeZhaoh0401Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Zhaoh0401Server will
// result in compilation errors.
type UnsafeZhaoh0401Server interface {
	mustEmbedUnimplementedZhaoh0401Server()
}

func RegisterZhaoh0401Server(s grpc.ServiceRegistrar, srv Zhaoh0401Server) {
	s.RegisterService(&Zhaoh0401_ServiceDesc, srv)
}

func _Zhaoh0401_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Zhaoh0401Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sample_module_0401.sample_package_0401.Zhaoh0401/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Zhaoh0401Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Zhaoh0401_ServiceDesc is the grpc.ServiceDesc for Zhaoh0401 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Zhaoh0401_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sample_module_0401.sample_package_0401.Zhaoh0401",
	HandlerType: (*Zhaoh0401Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Zhaoh0401_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Zhaoh0401.proto",
}
